const navStyle=document.createElement("style");navStyle.textContent=`main{transition:grid-template-columns .2s ease}body.sidebar-collapsed main{grid-template-columns:0 1fr}aside{background:var(--paper);transition:transform .2s ease,opacity .2s ease}body.sidebar-collapsed aside{transform:translateX(-100%);opacity:0;pointer-events:none}.sidebar-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.sidebar-head .icon-btn{display:none}.session{text-align:initial}.session-meta{font-size:12px;color:var(--muted);margin-top:3px}.match-preview{margin:10px 0 0;padding:9px 10px;border-radius:10px;background:#f5f0f5;color:#554d59;font-size:12px;line-height:1.55;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.open-session{width:100%;margin-top:10px;padding:9px 12px;border:1px solid var(--accent);border-radius:10px;background:var(--accent);color:#fff;font-weight:800}.sidebar-backdrop{display:none}.floating-menu{position:fixed;right:18px;bottom:18px;z-index:20;padding:11px 15px;border:1px solid #a58cab;border-radius:999px;background:#261f2d;color:#fff;font-weight:800;box-shadow:0 8px 28px #0004}@media(max-width:760px){main,body.sidebar-collapsed main{height:auto;display:block}.sidebar-head .icon-btn{display:block}aside,body.sidebar-collapsed aside{position:fixed;inset:0 auto 0 0;z-index:31;width:min(88vw,380px);max-height:none;border-right:1px solid var(--line);border-bottom:0;box-shadow:12px 0 36px #0003;transform:translateX(-105%);opacity:1;pointer-events:none}body.sidebar-open aside{transform:translateX(0);pointer-events:auto}.sidebar-backdrop{position:fixed;inset:0;z-index:30;border:0;background:#1f182688}body.sidebar-open .sidebar-backdrop{display:block}.viewer{min-height:70dvh}}`;document.head.append(navStyle);
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function openSidebar(){if(matchMedia("(max-width:760px)").matches)document.body.classList.add("sidebar-open");else document.body.classList.remove("sidebar-collapsed");$("menuBtn").setAttribute("aria-expanded","true")}
function closeSidebar(){if(matchMedia("(max-width:760px)").matches)document.body.classList.remove("sidebar-open");else document.body.classList.add("sidebar-collapsed");$("menuBtn").setAttribute("aria-expanded","false")}
["search","model","persona","folder","speaker"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",e=>{e.stopImmediatePropagation();renderList()},true));
$("menuBtn").onclick=()=>{const open=matchMedia("(max-width:760px)").matches?document.body.classList.contains("sidebar-open"):!document.body.classList.contains("sidebar-collapsed");open?closeSidebar():openSidebar()};$("closeSidebar").onclick=closeSidebar;$("sidebarBackdrop").onclick=closeSidebar;
const STORE="seishi-archive-v2",SETTINGS="seishi-settings-v2",DB_NAME="seishi-archive",DB_STORE="archive";let all=[],selected="",settings={userName:"あなた",assistantName:"ChatGPT",replacements:"",defaultsVersion:2};
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(DB_STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbGet(key){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE).objectStore(DB_STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbSet(key,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readwrite");tx.objectStore(DB_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbDelete(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readwrite");tx.objectStore(DB_STORE).delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function textOf(parts){if(typeof parts==="string")return parts;if(!Array.isArray(parts))return "";return parts.map(p=>typeof p==="string"?p:(p?.text||"")).join("\n")}
function modelOf(m){return m?.metadata?.model_slug||m?.metadata?.default_model_slug||m?.metadata?.model||"不明"}
function canonical(c){const map=c.mapping||{},out=[];let id=c.current_node;const seen=new Set;while(id&&map[id]&&!seen.has(id)){seen.add(id);const n=map[id],m=n.message;if(m&&["user","assistant"].includes(m.author?.role)){const text=textOf(m.content?.parts).trim();if(text)out.push({id:m.id||id,role:m.author.role,text,time:m.create_time||null,model:modelOf(m),hidden:false})}id=n.parent}return out.reverse()}
function guessPersona(c,msgs){const hay=((c.title||"")+"\n"+msgs.slice(0,8).map(x=>x.text).join("\n")).toLowerCase();if(/まんちゃん|温間満月/.test(hay))return "🌕 まんちゃん";if(/かげちゃん|影山誠実/.test(hay))return "🕯️ かげちゃん";if(/ひかちゃん|光谷虚実/.test(hay))return "🔦 ひかちゃん";return "未分類"}
function normalize(raw){return (Array.isArray(raw)?raw:raw.conversations||[]).map((c,i)=>{const messages=canonical(c);return{id:c.id||String(i),title:c.title||"無題の会話",time:c.create_time||0,updateTime:c.update_time||c.create_time||0,messages,models:[...new Set(messages.filter(x=>x.role==="assistant").map(x=>x.model))],persona:guessPersona(c,messages),folder:"未分類"}}).filter(x=>x.messages.length)}
function merge(incoming){const byId=new Map(all.map(x=>[x.id,x]));for(const fresh of incoming){const old=byId.get(fresh.id);if(!old){byId.set(fresh.id,fresh);continue}const edits=new Map(old.messages.map(m=>[m.id,m]));fresh.messages=fresh.messages.map(m=>{const e=edits.get(m.id);return e?{...m,text:e.text,hidden:e.hidden}:m});fresh.folder=old.folder||"未分類";fresh.persona=old.persona||fresh.persona;byId.set(fresh.id,fresh)}all=[...byId.values()].sort((a,b)=>b.time-a.time)}
async function save(){localStorage.setItem(SETTINGS,JSON.stringify(settings));try{await dbSet(STORE,all)}catch(err){console.error(err);alert("端末内への保存に失敗しました。空き容量をご確認ください。")}}
async function load(){try{const stored=await dbGet(STORE);if(stored)all=stored;else{const legacy=localStorage.getItem(STORE);if(legacy){all=JSON.parse(legacy)||[];await dbSet(STORE,all);localStorage.removeItem(STORE)}}settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS)||"{}"),defaultsVersion:2}}catch(err){console.error(err)}$("userName").value=settings.userName;$("assistantName").value=settings.assistantName;$("replacements").value=settings.replacements}
function replaceText(text){let out=String(text??"");for(const line of settings.replacements.split("\n")){const [from,...rest]=line.split("=>"),to=rest.join("=>");if(from?.trim()&&rest.length)out=out.split(from.trim()).join(to.trim())}return out}function nameOf(m,s){if(m.role==="user")return settings.userName||"ユーザー";return s.persona!=="未分類"?s.persona.replace(/^\S+\s*/,""):settings.assistantName||"ChatGPT"}function date(t){return t?new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(new Date(t*1000)):"日時不明"}
function visibleMessages(s){return s.messages.filter(m=>!m.hidden)}
function messageMatchesFilters(x,model,speaker){return !x.hidden&&(!model||(x.role==="assistant"&&x.model===model))&&(!speaker||x.role===speaker)}
function filtered(){const q=$("search").value.trim().toLowerCase(),m=$("model").value,p=$("persona").value,f=$("folder").value,speaker=$("speaker").value;return all.filter(s=>(!m||s.models.includes(m))&&(!p||s.persona===p)&&(!f||s.folder===f)&&(!speaker||s.messages.some(x=>messageMatchesFilters(x,m,speaker)))&&(!q||((!m&&!speaker&&replaceText(s.title).toLowerCase().includes(q))||s.messages.some(x=>messageMatchesFilters(x,m,speaker)&&replaceText(x.text).toLowerCase().includes(q)))))}
function matchInfo(s,q){if(!q)return{count:0,preview:""};const needle=q.toLowerCase(),model=$("model").value,speaker=$("speaker").value,hits=s.messages.filter(x=>messageMatchesFilters(x,model,speaker)&&replaceText(x.text).toLowerCase().includes(needle)),first=hits[0];if(!first)return{count:(!model&&!speaker&&replaceText(s.title).toLowerCase().includes(needle))?1:0,preview:"タイトルに一致"};const text=replaceText(first.text),at=text.toLowerCase().indexOf(needle),start=Math.max(0,at-55),end=Math.min(text.length,at+q.length+90);return{count:hits.length,preview:(start?"…":"")+text.slice(start,end)+(end<text.length?"…":"")}}
function renderList(){const rows=filtered(),q=$("search").value.trim();$("summary").textContent=`${rows.length} / ${all.length} セッション · ${all.reduce((n,s)=>n+s.messages.filter(m=>!m.hidden).length,0)} 発言`;$("sessions").innerHTML=rows.map(s=>{const hit=matchInfo(s,q);return`<article class="session ${s.id===selected?"active":""}"><strong>${esc(replaceText(s.title))}</strong><div class="session-meta">${esc(date(s.time))} · ${esc(s.persona)} · ${s.messages.filter(m=>!m.hidden).length}件${q?` · ${hit.count}件一致`:""}</div>${q?`<div class="match-preview">${mark(hit.preview,q)}</div>`:""}<button class="open-session" data-id="${esc(s.id)}">このセッションを開く</button></article>`}).join("")||'<p class="muted">該当する会話がありません。</p>';document.querySelectorAll(".open-session").forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();renderViewer();if(matchMedia("(max-width:760px)").matches)closeSidebar()})}
function mark(text,q){let h=esc(replaceText(text));if(!q)return h;const safe=q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return h.replace(new RegExp(safe,"gi"),x=>`<mark class="hit">${x}</mark>`)}
function renderViewer(){const s=all.find(x=>x.id===selected);if(!s)return;const q=$("search").value.trim(),model=$("model").value,speaker=$("speaker").value,shown=visibleMessages(s);$("viewer").innerHTML=`<article class="conversation"><div class="title-row"><div><h2>${esc(replaceText(s.title))}</h2><div class="meta">${esc(date(s.time))} · ${esc(s.models.join(", ")||"モデル不明")}</div></div><div class="tools"><button id="exportMd">Markdown</button><button id="exportJson">JSON</button></div></div><div class="session-fields"><label>ペルソナ<select id="sessionPersona">${["🕯️ かげちゃん","🌕 まんちゃん","🔦 ひかちゃん","未分類"].map(x=>`<option ${x===s.persona?"selected":""}>${x}</option>`).join("")}</select></label><label>フォルダ<input id="sessionFolder" value="${esc(s.folder||"未分類")}" list="folderList"></label><datalist id="folderList">${[...new Set(all.map(x=>x.folder))].map(x=>`<option value="${esc(x)}">`).join("")}</datalist></div>${shown.map(m=>`<div class="message ${m.role}" id="msg-${esc(m.id)}"><div class="message-head"><span class="label">${esc(nameOf(m,s))}${m.role==="assistant"?" · "+esc(m.model):""}</span><span><button class="edit icon-btn" data-mid="${esc(m.id)}">編集</button><button class="hide icon-btn" data-mid="${esc(m.id)}">非表示</button></span></div><div class="body">${mark(m.text,q&&messageMatchesFilters(m,model,speaker)?q:"")}</div></div>`).join("")||'<p class="muted">表示できる発言がありません。</p>'}<details class="hidden-box"><summary>非表示の発言（${s.messages.filter(m=>m.hidden).length}）</summary>${s.messages.filter(m=>m.hidden).map(m=>`<button class="restore" data-mid="${esc(m.id)}">${esc(nameOf(m,s))}の発言を戻す</button>`).join("")}</details></article>`;$("sessionPersona").onchange=e=>{s.persona=e.target.value;save();rebuildFilters();renderList();renderViewer()};$("sessionFolder").onchange=e=>{s.folder=e.target.value.trim()||"未分類";save();rebuildFilters();renderList()};document.querySelectorAll(".hide").forEach(b=>b.onclick=()=>{s.messages.find(m=>m.id===b.dataset.mid).hidden=true;save();renderViewer();renderList()});document.querySelectorAll(".restore").forEach(b=>b.onclick=()=>{s.messages.find(m=>m.id===b.dataset.mid).hidden=false;save();renderViewer();renderList()});document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>{const m=s.messages.find(x=>x.id===b.dataset.mid),next=prompt("発言を編集",m.text);if(next!==null){m.text=next;save();renderViewer();renderList()}});$("exportMd").onclick=()=>download(`${safeName(s.title)}.md`,toMarkdown(s),"text/markdown");$("exportJson").onclick=()=>download(`${safeName(s.title)}.json`,JSON.stringify(exportSession(s),null,2),"application/json");if(q)$("viewer").querySelector(".hit")?.scrollIntoView({block:"center"})}
function rebuildFilters(){const m=$("model").value,f=$("folder").value;$("model").innerHTML='<option value="">すべてのモデル</option>'+[...new Set(all.flatMap(x=>x.models))].sort().map(x=>`<option>${esc(x)}</option>`).join("");$("model").value=m;$("folder").innerHTML='<option value="">すべてのフォルダ</option>'+[...new Set(all.map(x=>x.folder||"未分類"))].sort().map(x=>`<option>${esc(x)}</option>`).join("");$("folder").value=f}
function exportSession(s){return{id:s.id,title:replaceText(s.title),created_at:s.time?new Date(s.time*1000).toISOString():null,persona:s.persona,folder:s.folder,messages:s.messages.filter(m=>!m.hidden).map(m=>({id:m.id,speaker:nameOf(m,s),role:m.role,model:m.role==="assistant"?m.model:null,created_at:m.time?new Date(m.time*1000).toISOString():null,text:replaceText(m.text)}))}}function toMarkdown(s){const x=exportSession(s);return `# ${x.title}\n\n- 日時: ${x.created_at||"不明"}\n- ペルソナ: ${x.persona}\n- フォルダ: ${x.folder}\n\n`+x.messages.map(m=>`## ${m.speaker}${m.model?`（${m.model}）`:""}\n\n${m.text}`).join("\n\n")+"\n"}function safeName(x){return replaceText(x).replace(/[\\/:*?"<>|]/g,"_").slice(0,80)||"conversation"}function download(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("file").onchange=async e=>{const files=[...e.target.files],failed=[];let count=0;for(const f of files){try{const n=normalize(JSON.parse(await f.text()));count+=n.length;merge(n)}catch{failed.push(f.name)}}await save();selected=selected||all[0]?.id||"";rebuildFilters();renderList();renderViewer();e.target.value="";alert(`${files.length}ファイル・${count}セッションを統合し、端末内に保存しました。${failed.length?` 読めなかったファイル: ${failed.join(", ")}`:""}`)};
["search","model","persona","folder","speaker"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",()=>{renderList();renderViewer()}));$("settingsBtn").onclick=()=>$("settings").showModal();$("saveSettings").onclick=()=>{settings={userName:$("userName").value.trim()||"ユーザー",assistantName:$("assistantName").value.trim()||"ChatGPT",replacements:$("replacements").value};save();renderList();renderViewer()};$("clearArchive").onclick=async()=>{if(confirm("端末内に保存した会話と編集内容をすべて消しますか？")){await dbDelete(STORE);localStorage.removeItem(STORE);all=[];selected="";$("settings").close();rebuildFilters();renderList();$("viewer").innerHTML='<div class="empty"><div class="moon">◐</div><h2>端末内データを消去しました</h2></div>'}};(async()=>{await load();selected=all[0]?.id||"";rebuildFilters();renderList();if(selected)renderViewer();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js")})();
