const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const STORE="seishi-archive-v2",SETTINGS="seishi-settings-v2";let all=[],selected="",settings={userName:"あなた",assistantName:"ChatGPT",replacements:"",defaultsVersion:2};
function textOf(parts){if(typeof parts==="string")return parts;if(!Array.isArray(parts))return "";return parts.map(p=>typeof p==="string"?p:(p?.text||"")).join("\n")}
function modelOf(m){return m?.metadata?.model_slug||m?.metadata?.default_model_slug||m?.metadata?.model||"不明"}
function canonical(c){const map=c.mapping||{},out=[];let id=c.current_node;const seen=new Set;while(id&&map[id]&&!seen.has(id)){seen.add(id);const n=map[id],m=n.message;if(m&&["user","assistant"].includes(m.author?.role)){const text=textOf(m.content?.parts).trim();if(text)out.push({id:m.id||id,role:m.author.role,text,time:m.create_time||null,model:modelOf(m),hidden:false})}id=n.parent}return out.reverse()}
function guessPersona(c,msgs){const hay=((c.title||"")+"\n"+msgs.slice(0,8).map(x=>x.text).join("\n")).toLowerCase();if(/まんちゃん|温間満月/.test(hay))return "🌕 まんちゃん";if(/かげちゃん|影山誠実/.test(hay))return "🕯️ かげちゃん";if(/ひかちゃん|光谷虚実/.test(hay))return "🔦 ひかちゃん";return "未分類"}
function normalize(raw){return (Array.isArray(raw)?raw:raw.conversations||[]).map((c,i)=>{const messages=canonical(c);return{id:c.id||String(i),title:c.title||"無題の会話",time:c.create_time||0,updateTime:c.update_time||c.create_time||0,messages,models:[...new Set(messages.filter(x=>x.role==="assistant").map(x=>x.model))],persona:guessPersona(c,messages),folder:"未分類"}}).filter(x=>x.messages.length)}
function merge(incoming){const byId=new Map(all.map(x=>[x.id,x]));for(const fresh of incoming){const old=byId.get(fresh.id);if(!old){byId.set(fresh.id,fresh);continue}const edits=new Map(old.messages.map(m=>[m.id,m]));fresh.messages=fresh.messages.map(m=>{const e=edits.get(m.id);return e?{...m,text:e.text,hidden:e.hidden}:m});fresh.folder=old.folder||"未分類";fresh.persona=old.persona||fresh.persona;byId.set(fresh.id,fresh)}all=[...byId.values()].sort((a,b)=>b.time-a.time);save()}
function save(){localStorage.setItem(STORE,JSON.stringify(all));localStorage.setItem(SETTINGS,JSON.stringify(settings))}function load(){try{all=JSON.parse(localStorage.getItem(STORE))||[];settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS)||"{}"),defaultsVersion:2}}catch{}$("userName").value=settings.userName;$("assistantName").value=settings.assistantName;$("replacements").value=settings.replacements}
function replaceText(text){let out=String(text??"");for(const line of settings.replacements.split("\n")){const [from,...rest]=line.split("=>"),to=rest.join("=>");if(from?.trim()&&rest.length)out=out.split(from.trim()).join(to.trim())}return out}function nameOf(m,s){if(m.role==="user")return settings.userName||"ユーザー";return s.persona!=="未分類"?s.persona.replace(/^\S+\s*/,""):settings.assistantName||"ChatGPT"}function date(t){return t?new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(new Date(t*1000)):"日時不明"}
function visibleMessages(s){return s.messages.filter(m=>!m.hidden)}
function filtered(){const q=$("search").value.trim().toLowerCase(),m=$("model").value,p=$("persona").value,f=$("folder").value,speaker=$("speaker").value;return all.filter(s=>(!m||s.models.includes(m))&&(!p||s.persona===p)&&(!f||s.folder===f)&&(!speaker||s.messages.some(x=>!x.hidden&&x.role===speaker))&&(!q||(replaceText(s.title)+" "+s.messages.filter(x=>!x.hidden).map(x=>replaceText(x.text)).join(" ")).toLowerCase().includes(q)))}
function renderList(){const rows=filtered();$("summary").textContent=`${rows.length} / ${all.length} セッション · ${all.reduce((n,s)=>n+s.messages.filter(m=>!m.hidden).length,0)} 発言`;$("sessions").innerHTML=rows.map(s=>`<button class="session ${s.id===selected?"active":""}" data-id="${esc(s.id)}"><strong>${esc(replaceText(s.title))}</strong><span>${esc(date(s.time))} · ${esc(s.persona)} · ${s.messages.filter(m=>!m.hidden).length}件</span></button>`).join("")||'<p class="muted">該当する会話がありません。</p>';document.querySelectorAll(".session").forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();renderViewer()})}
function mark(text,q){let h=esc(replaceText(text));if(!q)return h;const safe=q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return h.replace(new RegExp(safe,"gi"),x=>`<mark class="hit">${x}</mark>`)}
function renderViewer(){const s=all.find(x=>x.id===selected);if(!s)return;const q=$("search").value.trim(),shown=visibleMessages(s);$("viewer").innerHTML=`<article class="conversation"><div class="title-row"><div><h2>${esc(replaceText(s.title))}</h2><div class="meta">${esc(date(s.time))} · ${esc(s.models.join(", ")||"モデル不明")}</div></div><div class="tools"><button id="exportMd">Markdown</button><button id="exportJson">JSON</button></div></div><div class="session-fields"><label>ペルソナ<select id="sessionPersona">${["🕯️ かげちゃん","🌕 まんちゃん","🔦 ひかちゃん","未分類"].map(x=>`<option ${x===s.persona?"selected":""}>${x}</option>`).join("")}</select></label><label>フォルダ<input id="sessionFolder" value="${esc(s.folder||"未分類")}" list="folderList"></label><datalist id="folderList">${[...new Set(all.map(x=>x.folder))].map(x=>`<option value="${esc(x)}">`).join("")}</datalist></div>${shown.map(m=>`<div class="message ${m.role}" id="msg-${esc(m.id)}"><div class="message-head"><span class="label">${esc(nameOf(m,s))}${m.role==="assistant"?" · "+esc(m.model):""}</span><span><button class="edit icon-btn" data-mid="${esc(m.id)}">編集</button><button class="hide icon-btn" data-mid="${esc(m.id)}">非表示</button></span></div><div class="body">${mark(m.text,q)}</div></div>`).join("")||'<p class="muted">表示できる発言がありません。</p>'}<details class="hidden-box"><summary>非表示の発言（${s.messages.filter(m=>m.hidden).length}）</summary>${s.messages.filter(m=>m.hidden).map(m=>`<button class="restore" data-mid="${esc(m.id)}">${esc(nameOf(m,s))}の発言を戻す</button>`).join("")}</details></article>`;$("sessionPersona").onchange=e=>{s.persona=e.target.value;save();rebuildFilters();renderList();renderViewer()};$("sessionFolder").onchange=e=>{s.folder=e.target.value.trim()||"未分類";save();rebuildFilters();renderList()};document.querySelectorAll(".hide").forEach(b=>b.onclick=()=>{s.messages.find(m=>m.id===b.dataset.mid).hidden=true;save();renderViewer();renderList()});document.querySelectorAll(".restore").forEach(b=>b.onclick=()=>{s.messages.find(m=>m.id===b.dataset.mid).hidden=false;save();renderViewer();renderList()});document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>{const m=s.messages.find(x=>x.id===b.dataset.mid),next=prompt("発言を編集",m.text);if(next!==null){m.text=next;save();renderViewer();renderList()}});$("exportMd").onclick=()=>download(`${safeName(s.title)}.md`,toMarkdown(s),"text/markdown");$("exportJson").onclick=()=>download(`${safeName(s.title)}.json`,JSON.stringify(exportSession(s),null,2),"application/json");if(q)$("viewer").querySelector(".hit")?.scrollIntoView({block:"center"})}
function rebuildFilters(){const m=$("model").value,f=$("folder").value;$("model").innerHTML='<option value="">すべてのモデル</option>'+[...new Set(all.flatMap(x=>x.models))].sort().map(x=>`<option>${esc(x)}</option>`).join("");$("model").value=m;$("folder").innerHTML='<option value="">すべてのフォルダ</option>'+[...new Set(all.map(x=>x.folder||"未分類"))].sort().map(x=>`<option>${esc(x)}</option>`).join("");$("folder").value=f}
function exportSession(s){return{id:s.id,title:replaceText(s.title),created_at:s.time?new Date(s.time*1000).toISOString():null,persona:s.persona,folder:s.folder,messages:s.messages.filter(m=>!m.hidden).map(m=>({id:m.id,speaker:nameOf(m,s),role:m.role,model:m.role==="assistant"?m.model:null,created_at:m.time?new Date(m.time*1000).toISOString():null,text:replaceText(m.text)}))}}function toMarkdown(s){const x=exportSession(s);return `# ${x.title}\n\n- 日時: ${x.created_at||"不明"}\n- ペルソナ: ${x.persona}\n- フォルダ: ${x.folder}\n\n`+x.messages.map(m=>`## ${m.speaker}${m.model?`（${m.model}）`:""}\n\n${m.text}`).join("\n\n")+"\n"}function safeName(x){return replaceText(x).replace(/[\\/:*?"<>|]/g,"_").slice(0,80)||"conversation"}function download(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("file").onchange=async e=>{const files=[...e.target.files],failed=[];let count=0;for(const f of files){try{const n=normalize(JSON.parse(await f.text()));count+=n.length;merge(n)}catch{failed.push(f.name)}}selected=selected||all[0]?.id||"";rebuildFilters();renderList();renderViewer();e.target.value="";alert(`${files.length}ファイル・${count}セッションを統合しました。${failed.length?` 読めなかったファイル: ${failed.join(", ")}`:""}`)};
["search","model","persona","folder","speaker"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",()=>{renderList();renderViewer()}));$("settingsBtn").onclick=()=>$("settings").showModal();$("saveSettings").onclick=()=>{settings={userName:$("userName").value.trim()||"ユーザー",assistantName:$("assistantName").value.trim()||"ChatGPT",replacements:$("replacements").value};save();renderList();renderViewer()};$("clearArchive").onclick=()=>{if(confirm("端末内に保存した会話と編集内容をすべて消しますか？")){localStorage.removeItem(STORE);all=[];selected="";$("settings").close();rebuildFilters();renderList();$("viewer").innerHTML='<div class="empty"><div class="moon">◐</div><h2>端末内データを消去しました</h2></div>'}};load();selected=all[0]?.id||"";rebuildFilters();renderList();if(selected)renderViewer();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
